function nav_public()
{
	document.writeln('<div class="header">');
	document.writeln('<div class="nav_opacity">');
	document.writeln('</div>');
    document.writeln('<div class="nav">');
    document.writeln('<a href="index-3.html"/*tpa=http://gjqt3.wangyuan.com/index.html*/ class="logo"></a>');
    document.writeln('<div class="icon-box">');
    document.writeln('<a href="https://weibo.com/u/6394134151" target="_blank" class="wb">');
    document.writeln('<span></span>');
    document.writeln('</a>');
    document.writeln('<a href="javascript:;" class="wx">');
    document.writeln('<span></span>');
    document.writeln('</a>');
    document.writeln('</div>');
    document.writeln('<ul class="navlist">');
    document.writeln('<li>');
    document.writeln('<p><a href="index-3.html"/*tpa=http://gjqt3.wangyuan.com/index.html*/>官网首页</a></p>');
    document.writeln('</li>');
    document.writeln('<li>');
    document.writeln('<p><a href="javascript:;">新闻资讯</a></p>');
    document.writeln('<div class="navlist--nav">');
    document.writeln('<a href="allnews.shtml.htm"/*tpa=http://gjqt3.wangyuan.com/info/allnews.shtml*/ target="_blank">最新</a>');
    document.writeln('<a href="news.shtml.htm"/*tpa=http://gjqt3.wangyuan.com/info/news.shtml*/ target="_blank">新闻</a>');
    document.writeln('<a href="notice.shtml.htm"/*tpa=http://gjqt3.wangyuan.com/info/notice.shtml*/ target="_blank">公告</a>');
    document.writeln('</div>');
    document.writeln('</li>');
    document.writeln('<li>');
    document.writeln('<p><a href="download.html"/*tpa=http://gjqt3.wangyuan.com/library/download.html*/ target="_blank">游戏下载</a></p>');
    document.writeln('</li>');
    document.writeln('<li>');
    document.writeln('<p><a href="javascript:;">游戏资料</a></p>');
    document.writeln('<div class="navlist--nav">');
    document.writeln('<a href="bl.html"/*tpa=http://gjqt3.wangyuan.com/character/bl.html*/ target="_blank">主角介绍</a>');
    document.writeln('<a href="index-1.html"/*tpa=http://gjqt3.wangyuan.com/zt/feature/index.html*/ target="_blank">游戏特色</a>');
    document.writeln('<a href="yl.html"/*tpa=http://gjqt3.wangyuan.com/library/maps/yl.html*/ target="_blank">场景风物</a>');
    document.writeln('</div>');
    document.writeln('</li>');
    document.writeln('<li>');
    document.writeln('<p><a href="javascript:;">影音图库</a></p>');
    document.writeln('<div class="navlist--nav">');
    document.writeln('<a href="video.html"/*tpa=http://gjqt3.wangyuan.com/library/video.html*/ target="_blank">视频</a>');
    document.writeln('<a href="painting.html"/*tpa=http://gjqt3.wangyuan.com/library/painting.html*/ target="_blank">原画</a>');
    document.writeln('<a href="screenshot.html"/*tpa=http://gjqt3.wangyuan.com/library/screenshot.html*/ target="_blank">截图</a>');
    document.writeln('<a href="wallpaper.html"/*tpa=http://gjqt3.wangyuan.com/library/wallpaper.html*/ target="_blank">壁纸</a>');
    document.writeln('</div>');
    document.writeln('</li>');
    document.writeln('</ul>');
    document.writeln('</div>');
    document.writeln('</div>');
}
